[package]
name = "aoc2025_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
solver = { git = "https://github.com/JoBoCl/solver", version = "0.2.0" }
read = { git = "https://github.com/JoBoCl/read", version = "0.1.0" }
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"
